const { LANGUAGES } = require('./public/languages.js');

const languageMap = {
  'auto': 'en-US',
  'en': 'en-US',
  'es': 'es-ES',
  'fr': 'fr-FR',
  'de': 'de-DE',
  'it': 'it-IT',
  'pt': 'pt-BR',
  'ru': 'ru-RU',
  'ja': 'ja-JP',
  'ko': 'ko-KR',
  'zh': 'zh-CN',
  'zh-TW': 'zh-TW',
  'ar': 'ar-SA',
  'hi': 'hi-IN',
  'th': 'th-TH',
  'vi': 'vi-VN',
  'tr': 'tr-TR',
  'nl': 'nl-NL',
  'sv': 'sv-SE',
  'no': 'no-NO',
  'da': 'da-DK',
  'fi': 'fi-FI',
  'el': 'el-GR',
  'hu': 'hu-HU',
  'cs': 'cs-CZ',
  'ro': 'ro-RO',
  'bg': 'bg-BG',
  'hr': 'hr-HR',
  'uk': 'uk-UA',
  'pl': 'pl-PL',
  // African
  'af': 'af-ZA',
  'am': 'am-ET',
  'ny': 'ny-MW',
  'st': 'st-ZA',
  'sn': 'sn-ZW',
  'so': 'so-SO',
  'sw': 'sw-KE',
  'yo': 'yo-NG',
  'zu': 'zu-ZA',
  'xh': 'xh-ZA',
  'rw': 'rw-RW',
  'lg': 'lg-UG',
  'mg': 'mg-MG',
  'ti': 'ti-ER',
  // European
  'sq': 'sq-AL',
  'hy': 'hy-AM',
  'eu': 'eu-ES',
  'be': 'be-BY',
  'bs': 'bs-BA',
  'ca': 'ca-ES',
  'ceb': 'ceb-PH',
  'et': 'et-EE',
  'gl': 'gl-ES',
  'ka': 'ka-GE',
  'is': 'is-IS',
  'ga': 'ga-IE',
  'lv': 'lv-LV',
  'lt': 'lt-LT',
  'lb': 'lb-LU',
  'mk': 'mk-MK',
  'mt': 'mt-MT',
  'gd': 'gd-GB',
  'sr': 'sr-RS',
  'sk': 'sk-SK',
  'sl': 'sl-SI',
  'cy': 'cy-GB',
  'fo': 'fo-FO',
  'fy': 'fy-NL',
  'eo': 'eo',
  // Asian
  'lo': 'lo-LA',
  'km': 'km-KH',
  'my': 'my-MM',
  'tl': 'tl-PH',
  'id': 'id-ID',
  'ms': 'ms-MY',
  'bn': 'bn-BD',
  'pa': 'pa-IN',
  'ur': 'ur-PK',
  'ta': 'ta-IN',
  'te': 'te-IN',
  'mr': 'mr-IN',
  'gu': 'gu-IN',
  'kn': 'kn-IN',
  'ml': 'ml-IN',
  'or': 'or-IN',
  'ne': 'ne-NP',
  'mai': 'mai-IN',
  'bho': 'bho-IN',
  'new': 'new-NP',
  'taj': 'taj-NP',
  'si': 'si-LK',
  'dv': 'dv-MV',
  'as': 'as-IN',
  'bh': 'bh-IN',
  'sa': 'sa-IN',
  'fa': 'fa-IR',
  'he': 'he-IL',
  'ps': 'ps-AF',
  'az': 'az-AZ',
  'kk': 'kk-KZ',
  'ky': 'ky-KG',
  'tg': 'tg-TJ',
  'tk': 'tk-TM',
  'uz': 'uz-UZ',
  'mn': 'mn-MN',
  'dz': 'dz-BT',
  'tet': 'tet-TL',
  // Americas
  'ak': 'ak-GH',
  'ha': 'ha-NG',
  'ig': 'ig-NG',
  'la': 'la',
  'mi': 'mi-NZ',
  'qu': 'qu-PE',
  'ay': 'ay-BO',
  'gn': 'gn-PY',
};

let withVoices = 0;
let withoutVoices = 0;

LANGUAGES.forEach(lang => {
  if (languageMap[lang.code]) {
    withVoices++;
  } else {
    withoutVoices++;
  }
});

console.log(`Total languages: ${LANGUAGES.length}`);
console.log(`Languages with voices: ${withVoices}`);
console.log(`Languages without voices: ${withoutVoices}`);
